/**
 * API Endpoint Functions - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * Each function wraps the project's API client with the correct path, method,
 * and TypeScript types from api-generated.ts.
 */

import { get, post, put } from '@/lib/api/client';
import type { DefaultResponse } from '@/types/api';
import type {
  CreatePaymentBatchRequest,
  GetPaymentBatchesParams,
  GetPaymentsParams,
  ParkPaymentsRequest,
  PaymentBatchRead,
  PaymentBatchReadList,
  PaymentRead,
  PaymentReadList,
  PaymentsDashboardRead,
  UnparkPaymentsRequest,
} from '@/types/api-generated';

// ---------------------------------------------------------------------------
// Payment endpoints
// ---------------------------------------------------------------------------

/**
 * GET /v1/payments
 * Returns the full list of payments, optionally filtered by ClaimDate,
 * AgencyName, or Status.
 */
export function getPayments(
  params?: GetPaymentsParams,
): Promise<PaymentReadList> {
  return get<PaymentReadList>(
    '/v1/payments',
    params as Record<string, string | undefined>,
  );
}

/**
 * GET /v1/payments/{Id}
 * Returns a single payment by its numeric ID.
 */
export function getPayment(id: number): Promise<PaymentRead> {
  return get<PaymentRead>(`/v1/payments/${id}`);
}

/**
 * GET /v1/payments/dashboard
 * Returns the dashboard summary (status report, aging report, agency breakdown).
 */
export function getPaymentsDashboard(): Promise<PaymentsDashboardRead> {
  return get<PaymentsDashboardRead>('/v1/payments/dashboard');
}

/**
 * PUT /v1/payments/park
 * Parks (holds) a set of payments by ID.
 */
export function parkPayments(data: ParkPaymentsRequest): Promise<void> {
  return put<void>('/v1/payments/park', data);
}

/**
 * PUT /v1/payments/unpark
 * Un-parks (releases) a set of payments by ID.
 */
export function unparkPayments(data: UnparkPaymentsRequest): Promise<void> {
  return put<void>('/v1/payments/unpark', data);
}

// ---------------------------------------------------------------------------
// Payment Batch endpoints
// ---------------------------------------------------------------------------

/**
 * GET /v1/payment-batches
 * Returns the full list of payment batches, optionally filtered by Reference
 * or AgencyName.
 */
export function getPaymentBatches(
  params?: GetPaymentBatchesParams,
): Promise<PaymentBatchReadList> {
  return get<PaymentBatchReadList>(
    '/v1/payment-batches',
    params as Record<string, string | undefined>,
  );
}

/**
 * GET /v1/payment-batches/{Id}
 * Returns a single payment batch by its numeric ID.
 */
export function getPaymentBatch(id: number): Promise<PaymentBatchRead> {
  return get<PaymentBatchRead>(`/v1/payment-batches/${id}`);
}

/**
 * POST /v1/payment-batches
 * Creates a new payment batch from a list of payment IDs.
 * Requires the LastChangedUser header (passed via lastChangedUser param).
 */
export function createPaymentBatch(
  data: CreatePaymentBatchRequest,
  lastChangedUser: string,
): Promise<DefaultResponse> {
  return post<DefaultResponse>('/v1/payment-batches', data, lastChangedUser);
}

/**
 * POST /v1/payment-batches/{Id}/download-invoice-pdf
 * Downloads the invoice PDF for a payment batch as a Blob.
 */
export function downloadPaymentBatchInvoicePdf(id: number): Promise<Blob> {
  return post<Blob>(
    `/v1/payment-batches/${id}/download-invoice-pdf`,
    undefined,
    undefined,
  );
}

// ---------------------------------------------------------------------------
// Demo Administration endpoints
// ---------------------------------------------------------------------------

/**
 * POST /demo/reset-demo
 * Resets all demo data to its initial fixture state.
 * Returns void (no response body on success).
 */
export function resetDemo(): Promise<void> {
  return post<void>('/demo/reset-demo');
}
