/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 */

// Re-export DefaultResponse from api.ts so callers can import everything from one place.
export type { DefaultResponse } from '@/types/api';

// ---------------------------------------------------------------------------
// Payment Batch
// ---------------------------------------------------------------------------

export interface PaymentBatchRead {
  Id?: number;
  CreatedDate?: string;
  Status?: string;
  Reference?: string;
  LastChangedUser?: string;
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionAmount?: number;
  TotalVat?: number;
}

export interface PaymentBatchReadList {
  PaymentBatchList?: PaymentBatchRead[];
}

// ---------------------------------------------------------------------------
// Payment
// ---------------------------------------------------------------------------

export interface PaymentRead {
  Id?: number;
  Reference?: string;
  AgencyName?: string;
  ClaimDate?: string;
  AgentName?: string;
  LastChangedUser?: string;
  LastChangedDate?: string;
  AgentSurname?: string;
  BondAmount?: number;
  CommissionType?: string;
  GrantDate?: string;
  RegistrationDate?: string;
  Bank?: string;
  CommissionAmount?: number;
  VAT?: number;
  /** Post-normalisation contract: consumers always receive an object (see BA-4). */
  Status?: { StatusCode: string; Description?: string };
  BatchId?: number;
}

export interface PaymentReadList {
  PaymentList?: PaymentRead[];
}

// ---------------------------------------------------------------------------
// Dashboard / Reports
// ---------------------------------------------------------------------------

export interface PaymentStatusReportItem {
  Status?: string;
  PaymentCount?: number;
  TotalPaymentAmount?: number;
  CommissionType?: string;
  AgencyName?: string;
}

export interface ParkedPaymentsAgingReportItem {
  Range?: string;
  AgencyName?: string;
  PaymentCount?: number;
}

export interface PaymentsByAgencyReportItem {
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionCount?: number;
  Vat?: number;
}

export interface PaymentsDashboardRead {
  PaymentStatusReport?: PaymentStatusReportItem[];
  ParkedPaymentsAgingReport?: ParkedPaymentsAgingReportItem[];
  TotalPaymentCountInLast14Days?: number;
  PaymentsByAgency?: PaymentsByAgencyReportItem[];
}

// ---------------------------------------------------------------------------
// Inline request body types extracted from path operations
// ---------------------------------------------------------------------------

/** Request body for POST /v1/payment-batches */
export interface CreatePaymentBatchRequest {
  PaymentIds?: number[];
}

/** Request body for PUT /v1/payments/park */
export interface ParkPaymentsRequest {
  PaymentIds?: number[];
}

/** Request body for PUT /v1/payments/unpark */
export interface UnparkPaymentsRequest {
  PaymentIds?: number[];
}

// ---------------------------------------------------------------------------
// Query parameter shapes for list endpoints
// ---------------------------------------------------------------------------

export interface GetPaymentsParams {
  ClaimDate?: string;
  AgencyName?: string;
  Status?: string;
}

export interface GetPaymentBatchesParams {
  Reference?: string;
  AgencyName?: string;
}
